name: CI

on:
  push:
    branches: [main, staging]
  pull_request:

jobs:
  build-image:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2

      - name: Login to Github registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push backend
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ghcr.io/niwla23/iconcaps:latest

  compile_icons:
    runs-on: ubuntu-latest
    needs: [build-image]
    name: Compile all svg icons to keycaps
    steps:
      - name: Run the build process with Docker
        uses: addnab/docker-run-action@v3
        with:
            image: ghcr.io/niwla23/iconcaps:latest
            options: -v ${{ github.workspace }}/keycaps:/usr/src/app/target

      - uses: actions/upload-artifact@v3
        with:
          name: keycaps
          path: keycaps